name: INDEX.HTML validation
on:
  pull_request:
    branches:
      - develop
jobs:
  validate_index_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm i w3c-html-validator -g

      - name: Validate HTML
        run: html-validator --quiet index.html


        

