name: INDEX.HTML validation
on:
  workflow_dispatch:
jobs:
  validate_index_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install -g html-validate

      - name: Validate HTML
        run: html-validate --formatter stylish index.html

        

